### ISSUE TITLE
[BUG] DatabaseWriter does not commit before finalize

### ISSUE THREAD

**Issue by paul-gould** [mabel-dev/mabel#398]
**Describe the bug**
DatabaseWriter does not commit before executing `finalize()` method, so any uncommitted records are dropped.

Adding `self.commit()` at the top of the `finalize` method fixes this.

**Comment by paul-gould** [comment]
Actually, I'm not sure it's quite that simple as I don't think the database transaction gets committed between running the DatabaseWriter `commit()` and `finalize()`. So if `finalize()` wants to act on the saved records (e.g. running an upsert query from a staging table that the writer has written to), then it doesn't have access to the complete recordset.

**Comment by joocer** [comment]
You can either provide a 'finalizer' function which is called, it'll be pretty basic with that approach. Or you can override the finalize function in your own class. If your writer is doing something non trivial, you probably want to write your own finalized in your class.

**Comment by paul-gould** [comment]
Thanks. I was just about to delete that comment as I've realised I was calling my upsert function before calling the inner_writer's finalize. Hence the discrepancy with the records. D'Oh.

**Comment by joocer** [comment]
I've updated the finalizer to include commit, because that was a bug either way
