### ISSUE TITLE
[BUG] Reader doesn't read .txt files

### ISSUE THREAD

**Issue by gva-jjoyce** [mabel-dev/mabel#42]
**Describe the bug**
The Writer can write .txt files but these appear to be being ignored by the Reader.

**To Reproduce**
Steps to reproduce the behaviour:
1 Configure a Writer to write a 'text' format dataset
2 Use a Reader to read the dataset
3 Read zero records

**Expected behaviour**
The .txt files are read by the Reader

**Environment (please complete the following information):**
 - Version = 0.4.24

**Comment by joocer** [comment]
`.txt` is a valid extension. suggest the issue was the format of the file (Reader assumes JSON lines).
