### ISSUE TITLE
[BUG] step_back_days of 0 should fail if no data is found

### ISSUE THREAD

**Issue by gva-jjoyce** [mabel-dev/mabel#43]
**Describe the bug**
When using a 'step_back_days' of zero and there is no data for today, the reader should actively fail

**To Reproduce**
1 Set up a Reader to read a date where there is no data and a 'step_back_days' of zero
2 Execute the Reader

**Expected behaviour**
Active failure, rather than a Debug message

**Environment (please complete the following information):**
 - Version = 0.4.24

**Comment by joocer** [comment]
0 is currently used as the 'off' value for this feature, changing this to a negative value should resolve.

**Comment by joocer** [comment]
fixed in v0.4.25
