### ISSUE TITLE
[BUG] TODO message left in code

### ISSUE THREAD

**Issue by gva-jjoyce** [mabel-dev/mabel#79]
**Describe the bug**

This message is printed "IF THE TRACEBACK CONTAINS ERRORS, DON'T FINALIZE"

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.
!! Be aware not to publish any sensitive information in what you upload.

**Environment (please complete the following information):**

**Additional context**

**Comment by joocer** [comment]
Fixed
